### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by rdebath** [Maumagnaguagno/MindFreak#1]
This program should print "Brainfuck Hello World!" 
As it stands it doesn't compile. If the second line is removed the "Hello World!" part prints the wrong string.
``` bf
+>
<>
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++.---
    ------[>++<-]>.<++++[>----<-]>-.++++++++.+++++.[-]<++++[->++++<]>+[-<+
    +++++>]<.+++++++++++++++.>++++++[<--->-]<.++++++++.--[--->+<]>---.[-]<
<-
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
[>]<+<[[-]<]
```

**Comment by Maumagnaguagno** [comment]
You are right, it only works in interpreter mode.
Probably a bug in the optimizations or bytecode, I will investigate and fix this issue as soon as possible.
Thanks for the feedback.
